export const scholarships = [
  { id:'tata', title:'Tata Undergraduate Scholarship', provider:'Tata Trusts', logo:'/assets/logo-tata-blue.png', amount:'₹50,000 / year', deadline:'10 Oct 2025', level:'Undergraduate', type:'Merit-based', field:'Engineering', description:'Financial support for meritorious undergraduate students across India.' },
  { id:'reliance', title:'Reliance Foundation Scholarship', provider:'Reliance Foundation', logo:'/assets/logo-reliance.png', amount:'₹2,00,000 / year', deadline:'12 Nov 2025', level:'Undergraduate', type:'Need-based', field:'Engineering', description:'Empowering India’s future leaders through education.' },
  { id:'sbi', title:'SBI Asha Scholarship', provider:'State Bank of India', logo:'/assets/logo-sbi.png', amount:'₹1,00,000 / year', deadline:'15 Nov 2025', level:'Postgraduate', type:'Need-based', field:'Medical', description:'Supporting bright minds for a better tomorrow.' },
  { id:'inspire', title:'INSPIRE Scholarship', provider:'Department of Science & Technology', logo:'/assets/logo-india.svg', amount:'₹80,000 / year', deadline:'25 Nov 2025', level:'Undergraduate', type:'Merit-based', field:'Science', description:'Scholarship for high-achieving science students.' },
  { id:'adani', title:'Adani Foundation Scholarship', provider:'Adani Foundation', logo:'/assets/logo-adani.png', amount:'₹75,000 / year', deadline:'30 Nov 2025', level:'Undergraduate', type:'Need-based', field:'Engineering', description:'Supporting education for a brighter and inclusive future.' },
  { id:'central', title:'Central Sector Scholarship', provider:'Ministry of Education', logo:'/assets/logo-india.svg', amount:'₹1,00,000 / year', deadline:'1 Dec 2025', level:'Undergraduate', type:'Government', field:'Science', description:'Support for students from economically weaker sections.' }
];
export const profileKeys=['education','course','grade','familyIncome','domicile'];
export function profileComplete(profile={}) { return profileKeys.every((key)=>String(profile[key]||'').trim()); }
export function getMatch(scholarship, profile={}) { const interests=`${profile.course||''} ${profile.careerInterest||''}`.toLowerCase(); const preference=String(profile.scholarshipType||'').toLowerCase(); const grade=Number.parseFloat(profile.grade); const income=Number.parseFloat(profile.familyIncome); let score=55+(interests.includes(scholarship.field.toLowerCase())?18:5)+(Number.isFinite(grade)?(grade>=80||grade>=8?12:6):0)+(preference===scholarship.type.toLowerCase()?8:0); if(scholarship.type==='Need-based') score+=Number.isFinite(income)&&income<=500000?12:3; return Math.min(score,96); }
