const appStyle=document.createElement('style');appStyle.textContent='#appMessage{position:fixed;right:24px;bottom:24px;z-index:9999;background:#4c1220;color:#fff;padding:14px 18px;border-radius:8px;box-shadow:0 8px 22px #0003;font:13px Inter,Arial,sans-serif;transform:translateY(110px);transition:transform .25s}#appMessage.show{transform:translateY(0)}';document.head.append(appStyle);
const KEY_ACCOUNT='scholarMateAccount';
const KEY_PROFILE='scholarMateProfile';
const KEY_SESSION='scholarMateSession';
const showMessage=(message)=>{let box=document.getElementById('appMessage');if(!box){box=document.createElement('div');box.id='appMessage';document.body.append(box)}box.textContent=message;box.classList.add('show');setTimeout(()=>box.classList.remove('show'),3200)};
const signupForm=document.getElementById('signupForm');
if(signupForm){signupForm.addEventListener('submit',(event)=>{event.preventDefault();const name=document.getElementById('signupName').value.trim();const email=document.getElementById('signupEmail').value.trim().toLowerCase();const phone=document.getElementById('signupPhone').value.trim();const role=document.getElementById('signupRole').value;const password=document.getElementById('signupPassword').value;const confirm=document.getElementById('signupConfirmPassword').value;const accepted=document.getElementById('termsAccepted').checked;if(!name||!email||!password){showMessage('Please fill in your name, email and password.');return}if(password.length<6){showMessage('Password must be at least 6 characters long.');return}if(password!==confirm){showMessage('Passwords do not match.');return}if(!accepted){showMessage('Please accept the Terms of Service and Privacy Policy.');return}localStorage.setItem(KEY_ACCOUNT,JSON.stringify({name,email,phone,role,password}));const profile=JSON.parse(localStorage.getItem(KEY_PROFILE)||'{}');localStorage.setItem(KEY_PROFILE,JSON.stringify({...profile,fullName:name,email,phone}));localStorage.setItem(KEY_SESSION,JSON.stringify({name,email,role}));window.location.href='profile.html'})}
const loginForm=document.getElementById('loginForm');
if(loginForm){loginForm.addEventListener('submit',(event)=>{event.preventDefault();const email=document.getElementById('loginEmail').value.trim().toLowerCase();const password=document.getElementById('password').value;const account=JSON.parse(localStorage.getItem(KEY_ACCOUNT)||'null');if(!account){showMessage('No account found. Please create an account first.');return}if(account.email!==email||account.password!==password){showMessage('Email or password is incorrect.');return}localStorage.setItem(KEY_SESSION,JSON.stringify({name:account.name,email:account.email,role:account.role}));window.location.href='profile.html'})}
document.querySelectorAll('[data-social-provider]').forEach(button=>button.addEventListener('click',()=>showMessage(`${button.dataset.socialProvider} sign-in needs a secure backend connection.`)));
document.querySelectorAll('[data-logout]').forEach(link=>link.addEventListener('click',()=>localStorage.removeItem(KEY_SESSION)));
document.querySelectorAll('[data-forgot-password]').forEach(link=>link.addEventListener('click',(event)=>{event.preventDefault();showMessage('For this frontend demo, please create a new account if you forgot your password.')}));
