const defaultAvatar='data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 160 160"%3E%3Crect width="160" height="160" fill="%23c6c8d4"/%3E%3Ccircle cx="80" cy="57" r="27" fill="white"/%3E%3Cpath d="M25 143c6-37 30-55 55-55s49 18 55 55" fill="white"/%3E%3C/svg%3E';
const ids=['fullName','gender','email','location','phone','state','dob','city']; const saved=JSON.parse(localStorage.getItem('scholarMateProfile')||'{}');
ids.forEach(id=>{if(saved[id]!==undefined)document.getElementById(id).value=saved[id]});
const setName=()=>{const name=document.getElementById('fullName').value||'Student User';document.getElementById('heroName').childNodes[0].nodeValue=name+' ';document.getElementById('topName').textContent=name;document.getElementById('heroLocation').textContent=document.getElementById('location').value||'Indore, Madhya Pradesh'};
const photo=saved.photo||defaultAvatar;document.getElementById('avatar').src=photo;document.getElementById('topAvatar').src=photo;setName();
document.getElementById('photoInput').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{document.getElementById('avatar').src=reader.result;document.getElementById('topAvatar').src=reader.result;saved.photo=reader.result;localStorage.setItem('scholarMateProfile',JSON.stringify(saved))};reader.readAsDataURL(file)});
document.getElementById('profileForm').addEventListener('submit',e=>{e.preventDefault();const active=document.querySelector('.tabs .selected').textContent;if(active==='Personal Information'){ids.forEach(id=>saved[id]=document.getElementById(id).value);setName()}else{document.querySelectorAll('[data-profile-field]').forEach(field=>{saved[field.dataset.profileField]=field.type==='file'?(field.files[0]?.name||saved[field.dataset.profileField]||''):field.type==='checkbox'?field.checked:field.value})}localStorage.setItem('scholarMateProfile',JSON.stringify(saved));const t=document.getElementById('toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)});

const updateCompletion=()=>{const groups=[ids,['education','course','institution','academicYear','grade'],['category','familyIncome','domicile'],['scholarshipType','studyLocation','careerInterest'],['marksheet']];const complete=groups.map(group=>group.every(id=>String(saved[id]||'').trim()));const value=complete.filter(Boolean).length*20;const percent=document.getElementById('percent');const progress=document.querySelector('.progress');percent.textContent=value+'%';progress.style.background=`conic-gradient(var(--wine) 0 ${value}%,#f6e9e7 ${value}% 100%)`;document.querySelectorAll('.completion li').forEach((item,index)=>item.classList.toggle('done',complete[index]))};
updateCompletion();
document.getElementById('profileForm').addEventListener('submit',updateCompletion);

const tabDetails={
  'Personal Information':'Tell us about yourself. This information helps us find the best scholarships for you.',
  'Academic Details':'Add your education details to receive scholarships that match your academic journey.',
  'Eligibility Details':'Share your eligibility information to discover the opportunities you qualify for.',
  'Preferences':'Choose your interests and preferences to personalize your scholarship recommendations.',
  'Documents':'Keep your important documents ready for a smooth scholarship application process.'
};
const tabs=document.querySelectorAll('.tabs button');
const personalFields=document.querySelector('.fields').innerHTML;
const field=(label,id,type='text',options='')=>`<label>${label}<span><i class="fa-solid fa-pen"></i>${options?`<select data-profile-field="${id}">${options}</select>`:`<input data-profile-field="${id}" type="${type}" value="${saved[id]||''}">`}</span></label>`;
const formSections={
  'Academic Details':()=>field('Current Education <b>*</b>','education','text','<option value="">Select education level</option><option>Bachelor’s Degree</option><option>Master’s Degree</option><option>Diploma</option><option>Class 12</option>')+field('Course / Specialization <b>*</b>','course')+field('Institute / University <b>*</b>','institution')+field('Current Year <b>*</b>','academicYear','text','<option value="">Select current year</option><option>1st Year</option><option>2nd Year</option><option>3rd Year</option><option>Final Year</option>')+field('Last Exam Percentage / CGPA <b>*</b>','grade','number')+field('Expected Graduation Year','graduationYear','number'),
  'Eligibility Details':()=>field('Category <b>*</b>','category','text','<option value="">Select category</option><option>General</option><option>OBC</option><option>SC</option><option>ST</option><option>EWS</option>')+field('Annual Family Income <b>*</b>','familyIncome','number')+field('Are you a person with disability?','disability','text','<option value="">Select option</option><option>No</option><option>Yes</option>')+field('Entrance Exam / Score','examScore')+field('Domicile State <b>*</b>','domicile','text','<option value="">Select state</option><option>Madhya Pradesh</option><option>Maharashtra</option><option>Delhi</option><option>Rajasthan</option>')+field('Additional Eligibility Notes','eligibilityNotes'),
  'Preferences':()=>field('Scholarship Type','scholarshipType','text','<option value="">Select preference</option><option>Merit-based</option><option>Need-based</option><option>Government</option><option>Private</option>')+field('Preferred Study Location','studyLocation','text','<option value="">Select location</option><option>Anywhere in India</option><option>My State</option><option>My City</option>')+field('Career Interest / Field','careerInterest')+field('Monthly Scholarship Goal','scholarshipGoal','number')+field('Preferred Language','language','text','<option value="">Select language</option><option>English</option><option>Hindi</option><option>Both</option>')+field('Receive scholarship alerts?','alerts','text','<option value="">Select option</option><option>Yes</option><option>No</option>'),
  'Documents':()=>field('Aadhaar / ID Number','identityNumber')+field('Student ID Number','studentId')+`<label class="full">Latest Marksheet <b>*</b><span><i class="fa-solid fa-file-arrow-up"></i><input data-profile-field="marksheet" type="file" accept=".pdf,image/*"></span></label>`+`<label class="full">Income Certificate <span><i class="fa-solid fa-file-arrow-up"></i><input data-profile-field="incomeCertificate" type="file" accept=".pdf,image/*"></span></label>`
};
const activateTab=(tab)=>{const name=tab.textContent;tabs.forEach(item=>item.classList.toggle('selected',item===tab));document.getElementById('panelTitle').textContent=name;document.getElementById('panelCopy').textContent=tabDetails[name];document.querySelector('.fields').innerHTML=name==='Personal Information'?personalFields:formSections[name]();if(name==='Personal Information')ids.forEach(id=>{if(saved[id]!==undefined)document.getElementById(id).value=saved[id]});localStorage.setItem('scholarMateActiveTab',name)};
tabs.forEach(tab=>tab.addEventListener('click',()=>activateTab(tab)));
const rememberedTab=localStorage.getItem('scholarMateActiveTab');
if(rememberedTab){const tab=[...tabs].find(item=>item.textContent===rememberedTab);if(tab)activateTab(tab)};
